# Generated by Django 4.2 on 2023-05-11 03:52

import customerapp.create_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cell_color',
            field=customerapp.create_models.ColorCodeField(default='#F0F8FF', max_length=7),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
