# Generated by Django 4.2 on 2023-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_appointment_cell_color_appointment_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='phone_number',
        ),
    ]
