# Generated by Django 4.2 on 2023-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_remove_appointment_cell_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
