# Generated by Django 4.2 on 2023-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
