# Generated by Django 4.2 on 2023-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancel_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
