# Generated by Django 4.2 on 2023-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0004_remove_service_description_service_category'),
        ('customerapp', '0007_alter_appointment_cancel_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='salonmanager.service'),
        ),
    ]
