# Generated by Django 4.2 on 2023-05-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_remove_appointment_service_appointment_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
    ]
