# Generated by Django 4.2 on 2023-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_remove_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.branch'),
        ),
    ]
