# Generated by Django 4.2 on 2023-05-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0003_package_price_currency_product_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Hair Services', max_length=100),
        ),
    ]
