# Generated by Django 4.2 on 2023-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salonmanager', '0004_remove_service_description_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='services',
        ),
    ]
